# Generated by Django 3.0.8 on 2020-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_name', models.CharField(max_length=30)),
                ('cam_model', models.CharField(max_length=30)),
                ('cam_rentperday', models.CharField(max_length=30)),
                ('cam_owner', models.CharField(max_length=30)),
                ('cam_pic', models.ImageField(upload_to='images/')),
                ('whatsappno', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
    ]
