# Generated by Django 3.0.8 on 2020-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='cam_pic',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
