# Generated by Django 3.0.8 on 2020-08-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_remove_product_camdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dresstype', models.CharField(max_length=30)),
                ('dresssize', models.CharField(max_length=6)),
                ('dressowner', models.CharField(max_length=30)),
                ('dresscolour', models.CharField(max_length=30)),
                ('dressrentperday', models.CharField(max_length=30)),
                ('dresspic', models.ImageField(max_length=30, upload_to='')),
                ('whatsappno', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
    ]
