# Generated by Django 3.0.8 on 2020-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_product1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campic',
            field=models.ImageField(upload_to='newapp/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='camrentperday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product1',
            name='dresspic',
            field=models.ImageField(upload_to='newapp/images'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='dressrentperday',
            field=models.IntegerField(),
        ),
    ]
