# Generated by Django 3.0.8 on 2020-08-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20200822_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product1',
            old_name='dresscolour',
            new_name='itemcolour',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='dressowner',
            new_name='itemowner',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='dresspic',
            new_name='itempic',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='dressrentperday',
            new_name='itemrentperday',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='dresssize',
            new_name='itemsize',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='dresstype',
            new_name='itemtype',
        ),
    ]
