# Generated by Django 3.0.8 on 2020-08-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20200822_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cammodel',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='camname',
            new_name='itemowner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='campic',
            new_name='itempic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='camrentperday',
            new_name='itemrentperday',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camowner',
        ),
        migrations.AddField(
            model_name='product',
            name='itemsize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='', max_length=30),
        ),
    ]
