# Generated by Django 3.0.8 on 2020-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20200823_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemcolour',
            field=models.CharField(default='', max_length=30),
        ),
    ]
