# Generated by Django 3.0.8 on 2020-08-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20200823_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
