# Generated by Django 3.0.8 on 2020-08-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_auto_20200824_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
