# Generated by Django 3.0.8 on 2020-08-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_delete_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itemsize',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
