# Generated by Django 3.0.8 on 2020-08-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_auto_20200825_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsappno2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='adress',
            field=models.CharField(max_length=302),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cameras', 'Cameras'), ('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Chappals', 'Chappals'), ('Syndles', 'Syndles'), ('Vehicles', 'Vehicles'), ('Spectacles', 'Spectacles'), ('Home Appliances', 'Home Appliances'), ('Electronics', 'Electronics'), ('Other', 'Other')], default='Cameras', max_length=20),
        ),
    ]
