# Generated by Django 3.0.8 on 2020-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_auto_20200826_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('feedback', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
