# Generated by Django 3.0.8 on 2020-08-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_auto_20200828_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itempic',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
